### ISSUE TITLE
Web optimize profile image on https://mylesharrison.com/nlp4free/

### ISSUE THREAD

**Issue by MrCsabaToth** [mylesmharrison/nlp4free#1]
The "small" portrait on the website https://mylesharrison.com/nlp4free/ is kinda gigantic.
URL: https://mylesharrison.com/assets/img/profile_small.jpg 2035 x 2035.
Somehow when I reloaded the page Firefox rendering engine flashed your forehead for 20ms for whatever reason full screen :). That's how I noticed this. I'd advise resizing it to 98x98 (seems to be the effective size on wide screen) or similar, probably it'll help page loading speed. The banner image seems to be optimized (at least dimension wise).
Cheers!

**Comment by mylesmharrison** [comment]
Thanks Csaba, much obliged. I've downsized the image as you've suggested and now the page loads much faster. Thanks again!
